name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: luacheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup luarocks
        run: sudo apt-get install luarocks -q
      - name: Setup luacheck
        run: sudo luarocks install luacheck
      - name: Lint using luacheck
        run: luacheck lua/**/*.lua

  format:
    name: stylua
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Stylua Format
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          version: 0.11.2
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua/
